version: '3.7'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=scheduler
      - MYSQL_USER=root
      - MYSQL_PASSWORD=program1
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3310:3306"