server:
  port: 8090
  servlet:
    context-path: /user-management

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/user_management?useUnicode=true&characterEncoding=utf8
    username: max
    password: program1
    driver-class-name: org.mariadb.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    outOfOrder: true
    validateOnMigrate: false
    table: _SCHEMA_VERSION
    enabled: true

jwt:
  token:
    secret: jwtappdemo
    expired: 3600000