server:
  port: 8091
  servlet:
    context-path: /class-management

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/class_management?useUnicode=true&characterEncoding=utf8
    username: max
    password: program1
    driver-class-name: org.mariadb.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          max-interval: 5s
          multiplier: 2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  flyway:
#    outOfOrder: true
#    validateOnMigrate: false
#    table: _SCHEMA_VERSION
#    enabled: false

jwt:
  token:
    secret: jwtappdemo
    expired: 3600000